default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: Luiz2816
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: controle_acesso_development

test:
  <<: *default
  database: controle_acesso_test

production:
  <<: *default
  database: controle_acesso_production
  username: root
  password:
