default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("MYSQLHOST") %>
  port: <%= ENV.fetch("MYSQLPORT", 3306) %>
  username: <%= ENV.fetch("MYSQLUSER") %>
  password: <%= ENV.fetch("MYSQLPASSWORD") %>

development:
  <<: *default
  database: controle_acesso_development

test:
  <<: *default
  database: controle_acesso_test

production:
  <<: *default
  database: <%= ENV.fetch("MYSQLDATABASE") %>
