default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
  host: <%= ENV["MYSQLHOST"] %>
  port: <%= ENV["MYSQLPORT"] || 3306 %>

development:
  <<: *default
  database: controle_acesso_development

test:
  <<: *default
  database: controle_acesso_test

production:
  <<: *default
  database: <%= ENV["MYSQLDATABASE"] %>
